version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      # Mount everything except node_modules and lock files
      - ./app:/app/app
      - ./docs:/app/docs
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      # Named volume for node_modules
      - test-modules:/app/node_modules
      - test-modules2:/node_modules
    tty: true
    stdin_open: true 

volumes:
  test-modules: 