@host=http://localhost:28623/

### sample query
GET {{ host }}/api/data/entity/posts?limit=2&offset=1


### detailed
POST {{ host }}/api/data/entity/posts/query
Content-Type: application/json

{
   "limit": 1
}