name: Run Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.2.5"

      - name: Install dependencies
        working-directory: ./app
        run: bun install

      - name: Build
        working-directory: ./app
        run: bun run build:ci

      - name: Run Bun tests
        working-directory: ./app
        run: bun run test:bun

      - name: Run Node tests
        working-directory: ./app
        run: npm run test:node